Students Name in this group: Sridhar Ponnusamy, Kamakshi Mansukhani, Sarah Nowlan, Param Jaswal

# SCHOOL OF COMPUTER TECHNOLOGY


AASD 4001 Mathematical Concepts for Machine Learning

Labs week 2 


Excercise1

Exercise 1:
Open jupyter notebook LabExercise_4.ipynb and go through the following steps:
1. Using numpy arrays and slicing operations (:), define and print the following A, B, and C matrix:
A=[5 2 3 6 1 3 2 4 1] ,       B=[5 2 3 6 1 3 2 4 1] ,           C=[5 2 3 6 1 3 2 4 1] 


In [1]:
import numpy as np
A = np.matrix([[5,2,3], [6, 1, 3],[2,4,1]])

print("A=", A)
B= A[: , :]
print("B=",B)

C= A[0:3,0:3]
print("C=",C)

A= [[5 2 3]
 [6 1 3]
 [2 4 1]]
B= [[5 2 3]
 [6 1 3]
 [2 4 1]]
C= [[5 2 3]
 [6 1 3]
 [2 4 1]]


2. Define D matrix using numpy:
D=4 -7 4 5 6 -1 -4 2 5 


In [2]:
D= np.matrix([[4,-7,4],[6,-1,-4],[-4,2,5]])
D

matrix([[ 4, -7,  4],
        [ 6, -1, -4],
        [-4,  2,  5]])

3. Use numpy matmul to calculate AD and also DA. Are they equal?

In [5]:
AD= np.matmul(A,D)
print(AD)
DA=np.matmul(D,A)
print('They are not equal: ' ,  DA)

[[ 20 -31  27]
 [ 18 -37  35]
 [ 28 -16  -3]]
They are not equal:  [[-14  17  -5]
 [ 16  -5  11]
 [  2  14  -1]]


4. Manually calculate the determinant and inverse of B. Use NumPy to calculate the same entities and confirm that your manual calculation agrees with your results from the jupyter notebook.


In [6]:
#Determinant of B using Numpy

determinant_B= np.linalg.det(B)

In [7]:

#determinant_B= np.linalg.slogdet(B)

print(round(determinant_B))
#Inverse of B using Numpy
Inverse_Matrix_B=np.linalg.inv(B)
print(Inverse_Matrix_B)

11
[[-1.          0.90909091  0.27272727]
 [ 0.         -0.09090909  0.27272727]
 [ 2.         -1.45454545 -0.63636364]]


5. Use NumPy to calculate the inverse of D. Confirm that DD-1 and D-1D both are 3-by-3 identity matrices. Do you have any observations?


In [49]:
Inverse_Matrix_D=np.linalg.inv(D)
Inverse_Matrix_D

matrix([[ 0.02112676,  0.3028169 ,  0.22535211],
        [-0.09859155,  0.25352113,  0.28169014],
        [ 0.05633803,  0.14084507,  0.26760563]])

In [57]:

DD_1= np.matmul(D,Inverse_Matrix_D)
DD_1

matrix([[ 1.00000000e+00, -3.33066907e-16, -2.22044605e-16],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [ 2.77555756e-17,  1.66533454e-16,  1.00000000e+00]])

In [58]:
D_1D=np.matmul(Inverse_Matrix_D,D)
D_1D

matrix([[1.00000000e+00, 0.00000000e+00, 2.77555756e-16],
        [0.00000000e+00, 1.00000000e+00, 1.66533454e-16],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

Yes, Both are identity matrices.
Any number remains the same when multiplied by 1, any matrix remains the same when multiplied by the identity matrix.

In [60]:
#Identity Matrix
Identity_matrix=np.identity(3)
Identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Exercise 2:

1. Calculate the bag of words (without TF-IDF, just word counts) matrix for the following 5 phrases.
*/college student
*/airport taxi driver
*/Toronto art museum
*/life art
*/machine learning student


Hints: How many rows should be there? How many columns should be there?


In [15]:
#Source: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['college student','airport taxi driver','Toronto art museum','life art','machine learning student'
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

print(X.toarray())

['airport', 'art', 'college', 'driver', 'learning', 'life', 'machine', 'museum', 'student', 'taxi', 'toronto']
[[0 0 1 0 0 0 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 1 0 0 1]
 [0 1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 1 0 0]]


In [29]:
print(X.shape)

(5, 11)


2. Calculate the IDF for the words “college” and “art”.


In [31]:
#Source: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
from sklearn.feature_extraction.text import TfidfVectorizer
IDF_Calc=['college','text']

In [37]:
Tf_idf_vect=TfidfVectorizer() 

In [38]:
Tf_idf_vect.fit(IDF_Calc)

TfidfVectorizer()

In [39]:
#IDF values
print(vectorizer.idf_)

[1.40546511 1.40546511]
