<p style="font-family: Arial; font-size:3em;color:black;"> Lab W1 </p>

Students name in this Group:
Kamakshi Mansukhani
Param Jaswal
Sarah Nowlan
Sridhar Ponnusamy

In [30]:
# importing numpy
import numpy as np
from sys import getsizeof

In [19]:
#counts zeros in array and returns count
def zeroCheck(x):
    num = 0
    for i in x:
        if i == 0:
            num += 1  
    return num

In [25]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
A1 = np.array([1,2,3,5,0])
print(A1)
print("Amount of Zero elements is: ", zeroCheck(A1))

[1 2 3 5 0]
Amount of Zero elements is:  1


In [26]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
A2 = np.array([3,-1,3,7,2])
print(A2)
print("Amount of Zero elements is: ", zeroCheck(A2))

[ 3 -1  3  7  2]
Amount of Zero elements is:  0


In [27]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
A3 = np.array([0,0,0,0])
print(A3)
print("Amount of Zero elements is: ", zeroCheck(A3))

[0 0 0 0]
Amount of Zero elements is:  4


In [31]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
A4 = np.array([56,-2,7])
print(A4)
print("amount of memory requried for this array is: ", getsizeof(A4))

[56 -2  7]
amount of memory requried for this array is:  116


In [36]:
# Create a numpy array with 10 zeros and print the array.
A5 = np.zeros(10)
print(A5)
# Create a numpy array with 6 ones and print the array.
A6 = np.ones(6)
print(A6)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
A7 = np.ones(12)*3
print(A7)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [40]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
A8 = np.arange(8,21)
print(A8)
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
A9 = np.arange(8,21,2)
print(A9)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [72]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
A10 =np.random.normal(loc=2, scale=0.5, size=100)
print(A10)
print("Mean is: ", A10.mean(), " Max is: ", A10.max(), " Min is: ", A10.min(), "STD is: ", A10.std())
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

A11 =np.random.normal(loc=2, scale=0.5, size=1000)
print(A11)
print("Mean is: ", A11.mean(), " Max is: ", A11.max(), " Min is: ", A11.min(), "STD is: ", A11.std())

# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
A12 =np.random.normal(loc=2, scale=0.5, size=1000000)
print(A12)
print("Mean is: ", A12.mean(), " Max is: ", A12.max(), " Min is: ", A12.min(), "STD is: ", A12.std())
# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?


[1.09115023 1.99968727 2.4635052  2.25248729 2.52097893 0.96234759
 2.43451036 1.15683531 1.61667511 2.40663869 1.7680442  1.41395301
 1.60993125 1.86263384 1.35096919 1.8730379  2.45071798 1.58453043
 2.23821459 1.42912047 1.72651235 2.34293971 2.07859945 1.36234605
 1.76633454 2.9076994  1.72122357 2.79547954 1.78277869 3.11536874
 3.20343081 0.88743669 1.74611008 2.24927762 1.98878588 2.49542025
 2.22476708 2.81172559 1.88934735 2.30201212 2.48039323 1.78394149
 1.79398004 2.21241413 1.53446699 2.03037097 1.81182576 2.63393024
 1.2038598  1.35892338 2.57654933 1.70671607 1.59617045 1.2681611
 1.63105615 1.99457309 1.82880229 2.23225902 1.62578834 1.89969022
 1.34935465 2.72443965 2.5496206  2.10095087 1.85451986 2.15396777
 1.84199741 2.6038371  2.30582376 1.66388338 1.68210535 1.03012615
 2.65085915 1.94154173 2.80566908 2.02741599 2.56417631 2.6008192
 1.76776268 2.45492195 1.69210687 1.25937246 2.60939822 2.52191778
 1.73172621 1.69890542 1.82361512 1.16190109 2.49357347 1.589125