<p style="font-family: Arial; font-size:3em;color:black;"> Lab W1 </p>

Students name in this Group:Sridhar Ponnusamy, Kamakshi Mansukhani, Sarah Nowlan, Param Jaswal

In [2]:
# importing numpy
import numpy as np


In [22]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
s= np.array([1,2,3,4,5,0])
print(s)
#testing if all of its elements are non-zero.

p=np.all(s)
p

[1 2 3 4 5 0]


False

In [24]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
d= np.array([3, -1, 3, 7, 2])
print(d)
f=np.all(s)
f

[ 3 -1  3  7  2]


False

In [29]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
g=np.array([0,0,0,0])
print(g)

l=np.all(g)
print(l)


[0 0 0 0]
False


In [3]:
#https://www.geeksforgeeks.org/find-the-memory-size-of-a-numpy-array/(Referred)
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
t=np.array([56,-2,7])
print(t)

c=t.nbytes

print(c,"bytes")

%timeit(c) 

[56 -2  7]
12 bytes
41.3 ns ± 8.16 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [26]:
# Create a numpy array with 10 zeros and print the array.
ten_zeros=np.zeros(10)
#ten_zeros[:]=0
print('numpy array with 10 zeros:',ten_zeros)

# Create a numpy array with 6 ones and print the array.
six_ones= np.ones(6)
#six_ones[:]=1
print('numpy array with 6 ones:',six_ones)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
Twelve_3s=np.arange(12)
Twelve_3s[:]=3
print('numpy array with Twleve_3s:',Twelve_3s)

numpy array with 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
numpy array with 6 ones: [1. 1. 1. 1. 1. 1.]
numpy array with Twleve_3s: [3 3 3 3 3 3 3 3 3 3 3 3]


In [21]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
integers= np.arange(8,21)
print(integers)   
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
even_integers= np.arange(8,21,2)
print(even_integers)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [48]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
mean_m= 2
std_s= 0.5
random_elements = np.random.normal(loc=mean_m, scale=std_s, size=100)
min_value=np.argmin(random_elements)
max_value=np.argmin(random_elements)
print('numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5:',random_elements)
print('min_value:', min_value)
print('max_value:', max_value)
print('mean:',np.mean(random_elements))
print('std:',np.std(random_elements))



# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.




numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5: [1.79763171 1.83691867 2.24968794 2.03630633 1.67615384 1.53698035
 0.99255128 2.70501943 2.65283965 1.89655906 1.92451985 1.4615378
 0.70715453 1.59323945 2.36526191 2.55196481 2.50985812 2.1370993
 2.18859692 2.31746642 2.22934261 2.78923806 1.64264395 1.69358923
 1.79527968 2.00146231 2.40844064 2.90296425 1.43182157 1.50202097
 2.33423779 0.44229303 1.74362933 1.87211457 2.8272318  2.09035271
 2.11225349 1.61611472 1.55855515 1.88053702 1.54697917 1.54348377
 1.29271951 2.59250389 2.18586613 1.27568231 1.3994384  2.57979835
 2.31460312 1.24241438 2.64361128 2.67510501 2.21248575 2.71161178
 2.37773612 1.72029218 1.68174729 1.57585004 1.73375402 1.77462913
 2.49056055 3.0092591  2.0972071  3.03355467 2.16206361 2.93369474
 2.22809298 2.1084518  2.62833646 2.85638639 2.73099772 2.50649823
 1.60900253 1.51194535 1.62472169 2.57299982 2.40679402 2.69147097
 1.87394282 3.05772992 2.0398

In [51]:
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
mean_m= 2
std_s= 0.5
random_elements = np.random.normal(loc=mean_m, scale=std_s, size=1000)
min_value=np.argmin(random_elements)
max_value=np.argmax(random_elements)
print('numpy array consisting of 1000random elements from normal distribution with mean of 2 and std of 0.5:',random_elements)
print('min_value:', min_value)
print('max_value:', max_value)
print('mean:',np.mean(random_elements))
print('std:',np.std(random_elements))


numpy array consisting of 1000random elements from normal distribution with mean of 2 and std of 0.5: [1.53516055 2.93050202 1.53989483 1.9573831  2.02160443 1.5021119
 2.58996892 1.44042986 2.44870491 2.0649935  1.57833204 2.03656596
 2.63873863 1.82859773 1.76387357 1.75443241 2.27283864 1.17951202
 1.92065565 2.31008895 1.85762695 1.75418754 1.84157073 1.71529722
 1.72867826 1.31504557 2.98028327 2.95353437 2.12796752 2.43190413
 2.70686961 1.74900941 1.50296327 1.72269365 2.88572486 2.94650957
 2.28856846 2.12731392 1.9549801  1.64411398 1.34789794 2.43789137
 0.56775932 1.329378   1.66068146 2.26116328 1.77590643 1.01558987
 1.8469431  1.29482378 1.98524455 2.85199476 2.41582531 2.01199671
 2.48138203 1.13732379 1.74314077 1.96780657 1.00319809 1.63302824
 2.78117635 2.13656968 1.6937815  2.4770507  3.23237727 2.09078106
 2.51350608 2.03895284 2.27817854 1.33126096 2.09958093 1.83299981
 0.74923259 1.11137995 2.0669902  2.33574052 1.96607135 3.14369298
 2.54289242 2.24203864 1.810

In [52]:
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
mean_m= 2
std_s= 0.5
random_elements = np.random.normal(loc=mean_m, scale=std_s, size=1000000)
min_value=np.argmin(random_elements)
max_value=np.argmax(random_elements)
print('numpy array consisting of 1000random elements from normal distribution with mean of 2 and std of 0.5:',random_elements)
print('min_value:', min_value)
print('max_value:', max_value)
print('mean:',np.mean(random_elements))
print('std:',np.std(random_elements))

numpy array consisting of 1000random elements from normal distribution with mean of 2 and std of 0.5: [1.77666129 2.52129834 3.06297424 ... 2.09731015 2.40448129 2.62505838]
min_value: 433937
max_value: 65681
mean: 2.0004479154776322
std: 0.49977251879354834


## (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
1.100 samples, mean and standard deviation increases

2.1000 samples, mean and standard deviation decreases

3.1000000 samples, mean and std almost equal with predefined mean and std