# Week 2 Labs

## Exercise 1:
### Open jupyter notebook LabExercise_4.ipynb and go through the following steps:


In [7]:
import numpy as np


1. Using numpy arrays and slicing operations (:), define and print the following A, B, and C matrix:
A=[■(5&2&3@6&1&3@2&4&1)],       B=[■(5&2&3@6&1&3@2&4&1)],           C=[■(5&2&3@6&1&3@2&4&1)]

In [2]:
A = np.matrix('5,2,3 ; 6,1,3 ;2 ,4,1')
B = A
C = A
print(A) , print(B), print(C)

[[5 2 3]
 [6 1 3]
 [2 4 1]]
[[5 2 3]
 [6 1 3]
 [2 4 1]]
[[5 2 3]
 [6 1 3]
 [2 4 1]]


(None, None, None)

2. Define D matrix using numpy:
D=[■(4&-7&4@5&6&-1@-4&2&5)]

In [3]:
D = np.matrix('4,-7,4;5,6,-1;-4,2,5')
print(D)

[[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]


3. Use numpy matmul to calculate AD and also DA. Are they equal?

In [4]:
AD = np.matmul(A,D)
DA = np.matmul(D,A)
print(AD), print(DA)

[[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]
[[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]


(None, None)

matmul on matrix AD and DA are not the same

4. Manually calculate the determinant and inverse of B. Use numpy to calculate the same entities and confirm that your manual calculation agrees with your results from the jupyter notebook.

manual calcutlations: determinant = 11.
inverse Matrix =  | -1,  10/11 , 3/11  |
                  |  0,  -1/11  , 3/11 |
                  |  2 , -16/11 , -1/11|

In [11]:
Bdet = np.linalg.det(B)
Binv = np.linalg.inv(B)
print("Determinate of B is: ",Bdet) , print("Inverse of B is: "), print(Binv)
#similr answer. mine were rounded so less decimals. program more exact

Determinate of B is:  11.000000000000007
Inverse of B is: 
[[-1.00000000e+00  9.09090909e-01  2.72727273e-01]
 [-3.02788098e-17 -9.09090909e-02  2.72727273e-01]
 [ 2.00000000e+00 -1.45454545e+00 -6.36363636e-01]]


(None, None, None)

5. Use numpy to calculate the inverse of D. Confirm that 〖DD〗^(-1) and D^(-1) D both are 3-by-3 identity matrices. Do you have any observations?

In [18]:
Dinv = np.linalg.inv(D)
D1 = (D*D)^-1
D2 = (D^-1)*D
print("DD ^-1: "), print(D1), print("D^-1: "), print(D2)

DD ^-1: 
[[ 34  61 -44]
 [-55   0 -10]
 [ 25 -51  -8]]
D^-1: 
[[ 30  61 -51]
 [-59   0 -17]
 [ 21 -51 -15]]


(None, None, None, None)

# Exercise 2:


1. Calculate the bag of words (without TF-IDF, just word counts) matrix for the following 5 phrases.
•	college student
•	airport taxi driver
•	Toronto art museum
•	life art
•	machine learning student 
Hints: How many rows should be there? How many columns should be there?

There should be 5 rows as there are 5 phrases and 11 columns because there are 11 unique words

 college|studten|airport|taxi|driver|toronto|art|museum|life|mahcine|learning|
|   1       1       0     0     0      0      0     0    0     0        0    |
|   0       0       1     1     1      0      0     0    0     0        0    |
|   0       0       0     0     0      1      1     1    0     0        0    |
|   0       0       0     0     0      0      1     0    1     0        0    |
|   0       1       0     0     0      0      0     0    0     1        1    |

2. Calculate the IDF for the words “college” and “art”.

college TF = 1
college IDF = 1/11

art TF = 2
art IDF = 2/11
